### ISSUE TITLE
appveyor badge is wrong url

### ISSUE THREAD

**Issue by kellyselden** [joliss/node-fixturify#10]

**Comment by stefanpenner** [comment]
ah, its for: https://ci.appveyor.com/project/embercli/node-fixturify/settings/badges

**Comment by stefanpenner** [comment]
let me fix.

**Comment by stefanpenner** [comment]
https://github.com/joliss/node-fixturify/commit/756bd97b1fa56809a99bf7ce33c9076ed3d57db9

Should be correct now, thanks for catching!
