### ISSUE TITLE
Globs in readSync should behave the same as walk-sync

### ISSUE THREAD

**Issue by krisselden** [joliss/node-fixturify#12]
The glob options in readSync behaved unexpectedly and I worked around it by creating the pojo from walk-sync, when I get around to it, I'll submit a PR here to do the same thing.

https://github.com/broccolijs/broccoli-test-helper/blob/master/src/util.ts#L29

**Comment by stefanpenner** [comment]
@kellyselden mind taking a look?

**Comment by stefanpenner** [comment]
@krisselden, just confirming your suggestion is to use walkSync in node-fixturify as it handles these cases correctly, right?

**Comment by krisselden** [comment]
Yes, like the code I linked above
